"""remove column

Revision ID: 0f095157be58
Revises: 8d45c8d2c2db
Create Date: 2026-01-08 13:23:30.397145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f095157be58'
down_revision: Union[str, Sequence[str], None] = '8d45c8d2c2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_weeks_id'), table_name='program_weeks')
    op.drop_table('program_weeks')
    op.drop_index(op.f('ix_daily_usage_id'), table_name='daily_usage')
    op.drop_table('daily_usage')
    op.drop_index(op.f('ix_program_workouts_id'), table_name='program_workouts')
    op.drop_table('program_workouts')
    op.drop_index(op.f('ix_training_programs_id'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_strava_id'), table_name='users')
    op.drop_column('users', 'strava_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_strava_id'), 'users', ['strava_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_messages_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('training_programs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('training_programs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('goal', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('duration_weeks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='training_programs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='training_programs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_training_programs_id'), 'training_programs', ['id'], unique=False)
    op.create_table('program_workouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workout_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intensity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['program_weeks.id'], name=op.f('program_workouts_week_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('program_workouts_pkey'))
    )
    op.create_index(op.f('ix_program_workouts_id'), 'program_workouts', ['id'], unique=False)
    op.create_table('daily_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_usage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_usage_pkey'))
    )
    op.create_index(op.f('ix_daily_usage_id'), 'daily_usage', ['id'], unique=False)
    op.create_table('program_weeks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekly_goal', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.id'], name=op.f('program_weeks_program_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('program_weeks_pkey'))
    )
    op.create_index(op.f('ix_program_weeks_id'), 'program_weeks', ['id'], unique=False)
    # ### end Alembic commands ###
