"""Add Strava integration and profile fields

Revision ID: 3fab3848c76c
Revises: 
Create Date: 2025-10-15 20:46:07.597242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fab3848c76c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    op.add_column('users', sa.Column('strava_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('strava_athlete_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_strava_athlete_id'), 'users', ['strava_athlete_id'], unique=False)
    op.add_column('workouts', sa.Column('strava_id', sa.BigInteger(), nullable=True))
    op.add_column('workouts', sa.Column('moving_time', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('elapsed_time', sa.Integer(), nullable=True))
    op.add_column('workouts', sa.Column('total_elevation_gain', sa.Float(), nullable=True))
    op.add_column('workouts', sa.Column('suffer_score', sa.Integer(), nullable=True))
    op.alter_column('workouts', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_workouts_strava_activity_id'), table_name='workouts')
    op.create_index(op.f('ix_workouts_start_date'), 'workouts', ['start_date'], unique=False)
    op.create_index(op.f('ix_workouts_strava_id'), 'workouts', ['strava_id'], unique=True)
    op.drop_column('workouts', 'duration')
    op.drop_column('workouts', 'elevation_gain')
    op.drop_column('workouts', 'strava_activity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('strava_activity_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workouts', sa.Column('elevation_gain', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('workouts', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workouts_strava_id'), table_name='workouts')
    op.drop_index(op.f('ix_workouts_start_date'), table_name='workouts')
    op.create_index(op.f('ix_workouts_strava_activity_id'), 'workouts', ['strava_activity_id'], unique=True)
    op.alter_column('workouts', 'start_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('workouts', 'suffer_score')
    op.drop_column('workouts', 'total_elevation_gain')
    op.drop_column('workouts', 'elapsed_time')
    op.drop_column('workouts', 'moving_time')
    op.drop_column('workouts', 'strava_id')
    op.drop_index(op.f('ix_users_strava_athlete_id'), table_name='users')
    op.drop_column('users', 'strava_athlete_id')
    op.drop_column('users', 'strava_token_expires_at')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
