"""Add chat messages and daily usage tables

Revision ID: 73811b5adf4c
Revises: 7dba325d9399
Create Date: 2025-11-21 20:20:46.215603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73811b5adf4c'
down_revision: Union[str, Sequence[str], None] = '7dba325d9399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
